bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

big_3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('review_product/<int:product_id>/', views.review_product, name='review_product'),
    path('delete_review/<int:product_id>/<int:user_id>/', views.delete_review, name='delete_review'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True) # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category, Review


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-5'

class ReviewForm(forms.ModelForm):
    """
    A form for Reviews.
    """
    class Meta:
        # Set model
        model = Review
        # Set field names
        fields = ('rating', 'review')
        # Set field labels
        labels = {
            'rating': 'Rating',
            'review': 'Review',
        }

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, set autofocus on review field
        """
        super().__init__(*args, **kwargs)
        # Set placeholders
        placeholders = {
            'rating': 'Rating',
            'review': 'Review',
        }
        # Set autofocus to review field
        self.fields['review'].widget.attrs['autofocus'] = True
        # Loop through fields, add placeholders
        for field_name, placeholder in placeholders.items():
            # Add a * to placeholder if field is required
            if self.fields[field_name].required:
                placeholder_text = placeholder + "*"
            else:
                placeholder_text = placeholder
            # Set placeholder
            self.fields[field_name].widget.attrs[
                'placeholder'] = placeholder_text
            # Add review-input class
            self.fields[field_name].widget.attrs[
                'class'] = 'review-input'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category, Review
from .forms import ProductForm, ReviewForm

# Create your views here.

def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)
            
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)
    # Get Product Reviews
    product_reviews = Review.objects.filter(
        product=product).order_by("-rating")[:5]
    user_review = None
    # If user is authenticated, get User Review
    if request.user.is_authenticated:
        user_review = Review.objects.filter(
            product=product, user=request.user).first()


    context = {
        'product': product,
        'product_reviews': product_reviews,
		'user_review': user_review,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()
        
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


@login_required
def review_product(request, product_id):
    """ Review a Product """

    # Get Product object
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        # Get User Review for Product
        product_review = Review.objects.filter(
            product=product, user=request.user).first()
        # If Review exists
        if product_review:
            new_review = False
            # Instantiate ReviewForm from POST data and review object
            review_form = ReviewForm(request.POST, instance=product_review)
        else:
            new_review = True
            # Instantiate ReviewForm from POST data
            review_form = ReviewForm(request.POST)
        # If form is valid
        if review_form.is_valid():
            # If Review is new
            if new_review:
                # Create Review object
                review = review_form.save(commit=False)
                # Set Product
                review.product = product
                # Set User
                review.user = request.user
                # Save review
                review.save()
                # Success message
                messages.success(
                    request,
                    f'Review added for product: {product.name}.',
                    extra_tags='admin'
                )
            else:
                # Update Review
                review_form.save()
                # Success messsage
                messages.success(
                    request,
                    f'Review updated for product: {product.name}.',
                    extra_tags='admin'
                )
            # Redirect to Product detial page
            return redirect(reverse('product_detail', args=[product.id]))

        else:
            # If rating not set
            if not review_form['rating'].value():
                # Error message
                messages.error(
                    request,
                    'Error - please rate product to add review.',
                    extra_tags='admin'
                )
            else:
                # Error message
                messages.error(
                    request,
                    'Failed to add or edit review. Please check review form.',
                    extra_tags='admin'
                )

    else:
        # Get Review object
        product_review = Review.objects.filter(
            product=product, user=request.user).first()
        # If Review exists
        if product_review:
            # Instatiate ReviewForm from Review object
            review_form = ReviewForm(instance=product_review)
        else:
            # Instatiate blank ReviewForm
            review_form = ReviewForm
    from_profile = False
    # Get referer
    referer = (request.META.get('HTTP_REFERER', '/'))
    # Set from_profile if referred from Profile page
    if referer:
        rarray = referer.split('/')
        if rarray:
            rarray.reverse()
            if len(rarray) > 1:
                if rarray[1] == "profile":
                    from_profile = True
    # Get all Categories
    categories_all = Category.objects.all()
    # set semplate
    template = "products/review_product.html"
    # Set context
    context = {
        'product': product,
        'product_review': product_review,
        'review_form': review_form,
        'categories_all': categories_all,
        'from_profile': from_profile
    }
    # Render Product review page
    return render(request, template, context)


@login_required
def delete_review(request, product_id, user_id):
    """ Delete an existing Review """
    # Get Product object
    product = get_object_or_404(Product, pk=product_id)
    # Get User object
    user = get_object_or_404(User, pk=user_id)
    # Get Review object for Product and User
    review = get_object_or_404(Review, product=product, user=user)
    # If user is not a superuser
    if not request.user.is_superuser:
        # Error message
        messages.error(
            request,
            'Sorry, only store administrators can do that.',
            extra_tags='admin'
        )
        # Redirect to Product detail page
        return redirect(reverse('product_detail', args=[product.id]))
    # Delete Rdview
    review.delete()
    # Success message
    messages.success(
        request,
        f'User { user.username} review deleted for product: \
            {product.friendly_name}.',
        extra_tags='admin'
    )
    # Redirect to Product detail page
    return redirect(reverse('product_detail', args=[product.id]))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <!-- Add Product -->
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>
        <!-- Add Product Form -->
        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <!-- Navigation Buttons -->
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-5" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-5" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <!-- Add Image Function -->
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <!-- Edit a Product -->
    <div class="overlay"></div>
    <div class="container">
        <div class="row">

            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>
        <!-- Edit Product Form -->
        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <!-- Navigation Buttons -->
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-5" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-5" type="submit">Update Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <!-- Add Image Function -->
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    
{% endblock %}

{% block content %}
    <!-- Product Details -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <!-- Product Image -->
                <div class="image-container my-5">
                    {% if product.image %}
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                        {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <!-- Product Name -->
                <div class="product-details-container mb-5 mt-md-5">
                    <h2 class="mb-0">{{ product.name }}</h2>
                    <h3 class="mb-0 text-left font-weight-bold">${{ product.price }}</h3>
                    {% if product.category %}
                        <p class="small mt-1 mb-0">
                            <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                            </a>
                        </p>
                    {% endif %}
                    {% if product.rating %}
                    <!-- Product Rating -->
                    <div id="product-rating-stars" class="product-rating-stars" data-product-rating="{{ product.rating }}">
                        <i id="star-1" class="fas fa-star"></i>
                        <i id="star-2" class="fas fa-star"></i>
                        <i id="star-3" class="fas fa-star"></i>
                        <i id="star-4" class="fas fa-star"></i>
                        <i id="star-5" class="fas fa-star"></i>
                    </div>
                    {% else %}
                        <h4 class="text-muted">No Rating</h4>
                    {% endif %}
                    <!-- Product Description -->
                    <p class="mt-3">{{ product.description }}</p>
                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <!-- Product Sizes -->
                            {% with product.has_sizes as s %}
                            {% if s %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-5 w-50" name="product_size" id='id_product_size'>
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m" selected>M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <!-- Quantity Chooser -->
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-10" 
                                                data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ product.id }}"
                                            id="id_qty_{{ product.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-10"
                                                data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--  Add to bag btn -->
                            <div class="col-12">
                                <input type="submit" class="btn btn-black rounded-10 text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-12 text-center">
                <!-- Btn to Redirect back to the Products Page -->
                <h4>
                    <a href="{% url 'products' %}" class="back-button btn btn-lg text-uppercase py-3"><i class="fas fa-long-arrow-alt-left"></i>  Back to All Products</a>
                </h4>
            </div>
        </div>
        <hr class="w-50">
        <!-- Reviews -->
        <div class="text-center">
            <h2 class="logo-font">Reviews</h2>
            <hr class="w-50 mb-1">
        </div>
        <br>
        <!-- Product review -->
        {% if product_reviews %}
            {% for product_review in product_reviews %}
                <div class="col-12 w-30">
                    <!-- Btn that redirects to the ReviewForm -->
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'review_product' product.id %}" class="back-button btn rounded-10">Write a Review!</a>
                    {% else %}
                        <a href="{% url 'account_login' %}" class="back-button btn rounded-10">Write a Review!</a>
                    {% endif %}
                </div>
                <br>
                <div class="col-12 justify-content-center">
                    <!-- Displays the user that submitted the review -->
                    <div class="card">
                        <div class="card-header">
                            {{ product_review.user.username }}
                            {% if request.user.is_superuser %}
                                    <!-- Delete Review -->
                                    <span>
                                        <a id="reviewDeleteBtn{{product_review.user.id}}" href="#" role="button"
                                            class="text-black reviewDeleteBtn link-small px-1"
                                            data-confirm-modal-title="Delete"
                                            data-confirm-modal-content="Do you really want to delete {{product_review.user.username}} review for {{product.friendly_name}}?"
                                            data-confirm-modal-link="{% url 'delete_review' product.id product_review.user.id %}">
                                            Delete
                                        </a>
                                    </span>
                                {% endif %}
                        </div>
                        <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <!-- Rating -->
                            <span id="product-rating-stars_{{ product_review.id }}" class="product-rating-stars text-center px-1" data-product-rating="{{ product_review.rating}}">
                                <i id="{{ product_review.id }}_star-1" class="fas fa-star fa-sm"></i>
                                <i id="{{ product_review.id }}_star-2" class="fas fa-star fa-sm"></i>
                                <i id="{{ product_review.id }}_star-3" class="fas fa-star fa-sm"></i>
                                <i id="{{ product_review.id }}_star-4" class="fas fa-star fa-sm"></i>
                                <i id="{{ product_review.id }}_star-5" class="fas fa-star fa-sm"></i>
                            </span>
                            <br>
                            <br>
                            <!-- Product Review Text -->
                            <p>{{ product_review.review }}</p>
                        </blockquote>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <!-- Product Not Yet Reviewed -->
            <div class="col-12 text-center">
                <span class="text-small px-1"><i>Product not yet reviewed</i></span>
            </div> 
            <br>
            <div class="col-12 text-center">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'review_product' product.id %}" class="back-button btn rounded-10">Write a Review!</a>
                {% else %}
                    <a href="{% url 'account_login' %}" class="back-button btn rounded-10">Write a Review!</a>
                {% endif %}
            </div>
        {% endif %}    
        <br>
    </div>
{% endblock %}

{% block extrapostloadjs %}
<!-- Link to Products JavaScript -->
<script src="{% static 'products/js/products.js' %}"></script>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}